```plantuml
@startuml facilities-and-jurisdictions
skinparam componentStyle uml2
frame "mCSD Facility" {
  component forg as "mCSD Organization"
  component floc as "mCSD Location"
  forg -[hidden]-> floc 
}
frame "mCSD Jurisdiction" {
  component jorg as "mCSD Organization"
  component jloc as "mCSD Location"
  jorg -[hidden]-> jloc 
}
@enduml
```

```plantuml
@startuml multiple-hierarchies
skinparam componentStyle uml2
skinparam linetype ortho
frame state as "State (Jurisdiction)"
together {
  frame countya as "County A (Jurisdiction)"
  frame countyb as "County B (Jurisdiction)"
}
frame hospital as "Hospital (Facility)" 
frame clinica as "Clinic A (Facility)"
frame clinicb as "Clinic B (Facility)"
frame supplyhub as "State Supply Hub (Jurisdiction)"
frame depot as "Supply Depot (Jurisdiction)"
component report as "All Reporting (Organization)"
together {
  component hospreport as "Hospital Reporting (Organization)"
  component clinicreport as "Clinic Reporting (Organization)"
}
state <-- countya
state <-- countyb
countya <-- hospital
countya <-- clinica
countyb <-- clinicb
supplyhub <-- depot
depot <-- hospital
depot <-- clinica
depot <-- clinicb
report <-- hospreport
report <-- clinicreport
hospreport <-- hospital
clinicreport <-- clinica
clinicreport <-- clinicb
@enduml
```

```plantuml
@startuml simple-facility-registry
skinparam componentStyle uml2
skinparam linetype ortho

node registry as "Facility Registry" {
  component forg as "mCSD Organization"
  component floc as "mCSD Location"
  frame "mCSD Facility"
  frame "mCSD Jurisdiction"
}
together {
  node hmis as "Health Management Information System"
  node mobile as "Mobile App"
}
registry -[hidden]-> hmis
registry <-- hmis 
registry <-- mobile 

@enduml
```

```plantuml
@startuml simple-facility-registry-sequence
skinparam componentStyle uml2

participant "Facility Registry" as registry
participant "Health Management Information System" as hmis
participant "Mobile App" as mobile

group HMIS querying registry
hmis -> registry: <b>[ITI-90]</b> Find Matching Care Services Request
registry -> hmis: <b>[ITI-90]</b> Find Matching Care Services Response
end
group Mobile App querying registry
mobile -> registry: <b>[ITI-90]</b> Find Matching Care Services Request
registry -> mobile: <b>[ITI-90]</b> Find Matching Care Services Response
end

@enduml
```




```plantuml
@startuml simple-facility-services
skinparam componentStyle uml2
skinparam linetype ortho

node registry as "Facility Registry" {
  component forg as "mCSD Organization"
  component floc as "mCSD Location"
  component service as "mCSD HealthcareService"
  frame "mCSD Facility"
  frame "mCSD Jurisdiction"
}
together {
  node fms as "Facility Management System"
  node mobile as "Mobile App"
}
registry <--> fms 
registry <--> mobile 

@enduml
```


```plantuml
@startuml federated-facility-registry
skinparam componentStyle uml2
skinparam linetype ortho

node registry as "Central Facility Registry" {
  component forg as "mCSD Organization"
  component floc as "mCSD Location"
  frame "mCSD Facility"
  frame "mCSD Jurisdiction"
}

together {
  node sourcea as "Facility Source A"
  node sourceb as "Facility Source B"
  node sourcec as "Facility Source C"
}

node mobile as "Mobile App"


registry -[hidden]--> sourcea
registry -[hidden]-> mobile

registry <--> sourcea 
registry <--> sourceb 
registry <--> sourcec 

registry <--> mobile 

@enduml
```
```plantuml
@startuml federated-facility-registry-sequence
skinparam componentStyle uml2
skinparam linetype ortho

participant "Central Facility Registry" as registry

participant "Facility Source A" as sourcea 
participant "Facility Source B" as sourceb 
participant "Facility Source C" as sourcec 

participant "Mobile App" as mobile 

group Registry Pulls Updates From Sources
registry -> sourcea: <b>[ITI-91]</b> Request Care Services Updates Request
sourcea -> registry: <b>[ITI-91]</b> Request Care Services Updates Response
registry -> sourceb: <b>[ITI-91]</b> Request Care Services Updates Request
sourceb -> registry: <b>[ITI-91]</b> Request Care Services Updates Response
registry -> sourcec: <b>[ITI-91]</b> Request Care Services Updates Request
sourcec -> registry: <b>[ITI-91]</b> Request Care Services Updates Response
end

group Source A Pulls Update from Registry
sourcea -> registry: <b>[ITI-91]</b> Request Care Services Updates Request
registry -> sourcea: <b>[ITI-91]</b> Request Care Services Updates Response
end

group Mobile App querying registry
mobile -> registry: <b>[ITI-90]</b> Find Matching Care Services Request
registry -> mobile: <b>[ITI-90]</b> Find Matching Care Services Response
end

@enduml
```



```plantuml
@startuml federated-facility-services
skinparam componentStyle uml2
skinparam linetype ortho
top to bottom direction

node registry as "Central Facility Registry" {
  component forg as "mCSD Organization"
  component floc as "mCSD Location"
  component service as "mCSD HealthcareService"
  frame "mCSD Facility"
  frame "mCSD Jurisdiction"
}

node source as "Facility Source"

node hwr as "Health Worker Registry"

node app as "Reporting App"


registry -[hidden]--> source
registry -[hidden]-> app

registry <--> moh 
registry --> hwr 
registry <--> app 

@enduml
```

